### ISSUE TITLE
Broken with v0.2.0 of grocy integration

### ISSUE THREAD

**Issue by SebRut** [isabellaalstrom/lovelace-grocy-chores-card#10]
Version 0.2.0 of the grocy integration introduced a separate sensor for chores with an attribute `items` containing the chores serialized as json.

**Comment by Grimidor** [comment]
Just change line 162 from
      var chores = JSON.parse(entity.attributes);
to
      var chores = JSON.parse(entity.attributes.items);
and change the "entity:" to the new chores sensor and I think it will work again.

**Comment by Stooovie** [comment]
I still can't get it to work even with Grimidor's suggestion (HA 0.100.3 on Rpi4 Hassion docker):

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 292, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_device_update
    await self.async_update()
  File "/config/custom_components/grocy/binary_sensor.py", line 33, in async_update
    await self._client.async_update_expiring_products()
  File "/config/custom_components/grocy/__init__.py", line 199, in async_update_expiring_products
    self.client.expiring_products))
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 161, in expiring_products
    raw_expiring_product = self.volatile_stock().expiring_products
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy.py", line 158, in volatile_stock
    return self._api_client.get_volatile_stock()
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 314, in get_volatile_stock
    return CurrentVolatilStockResponse(parsed_json)
  File "/usr/local/lib/python3.7/site-packages/pygrocy/grocy_api_client.py", line 199, in __init__
    self._expiring_products = [CurrentStockResponse(product) for product in parsed_json.get('expiring_products')]
TypeError: 'NoneType' object is not iterable`

**Comment by imbaimbaimba** [comment]
I also cannot get it to work even with the suggestions. Also tried messing around with everything else I could google on the matter.

**Comment by cyberfly79** [comment]
In .js file 162. line overwrite
      var chores = JSON.parse(entity.attributes.chores);
to
      var chores = JSON.parse(entity.attributes.items);
(HA 0.100.2 in docker)

**Comment by Stooovie** [comment]
> In .js file 162. line overwrite
> var chores = JSON.parse(entity.attributes.chores);
> to
> var chores = JSON.parse(entity.attributes.items);
> (HA 0.100.2 in docker)

nope, doesn't help

**Comment by cyberfly79** [comment]
> > In .js file 162. line overwrite
> > var chores = JSON.parse(entity.attributes.chores);
> > to
> > var chores = JSON.parse(entity.attributes.items);
> > (HA 0.100.2 in docker)
> 
> nope, doesn't help

browser cache? rename file?

**Comment by markinsutton** [comment]
has anyone got this card to work? I have tried everything I know and just wondering if anyone can share how?

**Comment by Grimidor** [comment]
It works for me but it's a little shaky :-)
If I use it as:

    entity: sensor.grocy_chores
    type: 'custom:grocy-chores-card'

it works fine. If I use it like:

    entity: sensor.grocy_chores
    show_days: 1
    title: Uppgifter
    type: 'custom:grocy-chores-card'

It doesn't work in the iPhone app but it works on the computer.

And this is with line 162 of the .js file looking like this:
      var chores = JSON.parse(entity.attributes.items);

**Comment by markinsutton** [comment]
tried both of those solutions with no luck. I just get a rotating color circle, strange thing is that by checking sensor.grocy_chores state things show up in the items  so at a lost why the Card is not working. My feeling it is something to do with the grocy integration but not sure.  Had it working once before I installed the grocy integration from the community store but can't seem to go back.   


`attribution: Data from this is provided by grocy.
items: >-
  [{"_chore_id": 1, "_last_done_by": null, "_last_tracked_time": null, "_name":
  "Vacuum Floor", "_next_estimated_execution_time": "2019-11-14
  22:42:58+00:00"}]
unit_of_measurement: Chore(s)
friendly_name: grocy.chores
icon: 'mdi:format-quote-close'`

**Comment by Grimidor** [comment]
Have you changed line 162 in the .js file? Also check that the .gz file (in the same folder) contains the change as well.

**Comment by markinsutton** [comment]
I hadn't changed the .gz file so used 7-zip to extract the file as winrar wouldn't now change. I have restarted checked that files are changed confirmed but still no joy

**Comment by Grimidor** [comment]
Strange. 
Just for reference
I'm running:
Hass.io with HA 0.101.2
Card tools 0.4

Grocy Sensor 0.3
Lovelace Grocy Chores Card 0.1.1
Both installed from Home Assistant Community Store

**Comment by markinsutton** [comment]
Thanks. figured it out. I think that card tools needed to be in the same folder as this card. I had it installed but under another path. I have done so much changing of the configuration lost track.  doesn't make sense as the paths under resources where correct. 

Got it working that matters.

**Comment by Grimidor** [comment]
Great!
I have my card tools in a different path so that should be working. 

\config\www\plugins\card-tools.js 
\config\www\community\lovelace-grocy-chores-card\grocy-chores-card.js

But as you said. As long as it works :-)

**Comment by cyberfly79** [comment]
Rename the js file because I think there is a cache problem.

**Comment by Resterday** [comment]
I am having a similar problem, but when I add the custom card to my lovelace view the whole view doesn't render. 

I have tried everything i could think of and all of what was suggested here. Any help would be great! 

Here is what I have:
Hass.io with HA 0.101.2
Card tools 2.3
Grocy component 0.3
Lovelace Grocy Chores Card 0.1.1
All installed from Home Assistant Community Store

I tired modifying line 162 of the .js file to:
`var chores = JSON.parse(entity.attributes.items)`

**Comment by isabellaalstrom** [comment]
I don't know why I don't get notifications about issues anymore on Github.. So, sorry for the delay, I will try to look into it.
