### ISSUE TITLE
"Show Days" Option with Range Not Working Properly

### ISSUE THREAD

**Issue by ShadyBrk** [isabellaalstrom/lovelace-grocy-chores-card#122]
Using the "Show Days" option with a range with the provided syntax, (eg. 1..10), it only yields the items that are overdue. Incrementing the lower bound also does not change the end result. 

Code:
``````
type: custom:grocy-chores-card
entity:
  - sensor.grocy_chores
title: Chores Due in Next 30 Days
show_days: 1..30
show_quantity: 100
show_assigned: false
show_overflow: true
use_icons: true
use_long_date: true
show_last_tracked: true
use_24_hours: true
show_empty: false
show_divider: true
``````

Result:
![20230712](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/assets/113226092/f3b93dde-fb0d-42ba-a8c1-fae90bdddf4b)

**Comment by karwosts** [comment]
What version you have, are you opted into beta versions?

There hasn't been a major release in some time, and the show_days range feature is somewhat new and is in the beta releases only.
