### ISSUE TITLE
filter_user does not register multiple assigned users

### ISSUE THREAD

**Issue by kernel610** [isabellaalstrom/lovelace-grocy-chores-card#123]
The filter_user configuration on the chore card does not appear to work properly when multiple users are assigned to a chore. Chores can be assigned to more than one person in Grocy and it comes over as such in the integration; however the card only seems to recognize the first user when using filter_user.

**Expected Behavior**
1. Create a chore and assign to John (user 3) and Jane (user 4)
2. Integration feeds over with chore and "assignment_config: 3,4"
3. Create 2 separate chore cards, one using "filter_user: 3" and one using "filter_user: 4"
- Chore card using "filter_user: 3" will display the chore
- Chore card using "filter_user: 4" will not display the chore, despite it also being assigned to this user.

**Comment by karwosts** [comment]
I'm not so convinced that this is how the card should behave. I see in grocy chores it has a concept of "next execution assigned user", and it seems like for chores with multiple assignees, grocy picks a single user and assigns an execution to that user only, and that is what the card is displaying.

If the chore is assigned to both Bob and Alice, for each chore execution Grocy picks _either_ Bob or Alice as the next assigned user of the chore, and the grocy card displays that person. But it does not assign multiple people to a single execution.

**Comment by kernel610** [comment]
> I'm not so convinced that this is how the card should behave. I see in grocy chores it has a concept of "next execution assigned user", and it seems like for chores with multiple assignees, grocy picks a single user and assigns an execution to that user only, and that is what the card is displaying.
> 
> If the chore is assigned to both Bob and Alice, for each chore execution Grocy picks _either_ Bob or Alice as the next assigned user of the chore, and the grocy card displays that person. But it does not assign multiple people to a single execution.

Thank you for the clarification! I'm still new to Grocy so I did a little more testing and confirmed the behavior. You're correct that chores cannot have two people assigned and what I was seeing is the people that are part of the chore rotation. It appears the card filters based on the next_execution_assigned_to_user_id which updates based on the rotation configuration. Closing out this thread.
