### ISSUE TITLE
Only showing Overdue Chores

### ISSUE THREAD

**Issue by zanish** [isabellaalstrom/lovelace-grocy-chores-card#125]
I've just install and enabled the grocy_chores sensor. I have 13 chores showing in the integration but only 2 that are overdue are showing in the card. In addition after install the card is showing "e is undefined" while configuring in the YAML. I've tried both v3.6.0 and v3.5.1

**Comment by dgarcoe** [comment]
The same happened to me. I've installed v3.4.1 and the issue has been solved. Seems to me that something happens since 3.5.1 that causes this problem.

**Comment by Shashankpantiitbhilai** [comment]
please assign this to me

**Comment by karwosts** [comment]
If this is still an issue, please update to the latest version, and in your post include your card configuration yaml. 

I don't see this behavior on my card.

**Comment by dgarcoe** [comment]
I confirm that the issue is fixed for me with the latest version! It appeared to be broken also with 2023.10 but now it works OK, thanks!

**Comment by zanish** [comment]
Just updated and verified I'm now seeing all my expected Chores, thanks for the quick turn around!
