### ISSUE TITLE
Custom element does not exist

### ISSUE THREAD

**Issue by NickM-27** [isabellaalstrom/lovelace-grocy-chores-card#128]
I updated to the latest version and I am now seeing that the card is not being loaded at all. I checked browser logs and see this

![Screen Shot 2023-10-11 at 09 23 21 AM](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/assets/14866235/633e59f4-3834-45e7-b12e-7106dfd758f7)

**Comment by clintkev251** [comment]
Yeah, I'm seeing the same behavior

**Comment by scrambled2k3** [comment]
Same for me as well.

**Comment by robertfgoodworth** [comment]
Same here too,  was working well until the I updated to the latest HA.

**Comment by karwosts** [comment]
This is a duplicate of #94 and the issue is discussed extensively there.
