### ISSUE TITLE
UTC Time instead of local time

### ISSUE THREAD

**Issue by eracknaphobia** [isabellaalstrom/lovelace-grocy-chores-card#13]
I clicked track on both and it set it 5 hours in the future on the grocy side of things. Also, you can see the schedule for differs.

![image](https://user-images.githubusercontent.com/8268725/69298491-069ec300-0bdc-11ea-9739-12a3ec578c88.png)
![image](https://user-images.githubusercontent.com/8268725/69298507-14544880-0bdc-11ea-9358-1386e1cd9dd0.png)

**Comment by isabellaalstrom** [comment]
I will look this over when I have the time. The title infers to that the calculation should be done in utc?

**Comment by isabellaalstrom** [comment]
I would like to help with this but I need more information. What time zone are you in, what time should it be and what does it set it for? Is it still the same with latest version?

**Comment by cerebrate** [comment]
I have this same problem.

It's not strictly speaking a bug with lovelace-grocy-chores-card; you can see this if you comment out the 

`tracked_time: new Date()`

line in the relevant function, and observe that the problem's still there when you rely on the default [set here](https://github.com/custom-components/grocy/blob/develop/custom_components/grocy/__init__.py#L155) by the grocy custom component.

The fundamental issue seems to be [way down here](https://github.com/SebRut/pygrocy/blob/master/pygrocy/grocy_api_client.py#L336) in the pygrocy library, where it's submitting a Python datetime which contains a _local_ time, but without timezone information attached to it, which the Grocy API then parses as UTC - and so 11 am CST becomes 5 pm.

I'm working on a pull request against pygrocy as we speak.

**Comment by isabellaalstrom** [comment]
Thank you @cerebrate ! I will look at the pr as soon as I can!

**Comment by cerebrate** [comment]
pygrocy PR is here: https://github.com/SebRut/pygrocy/pull/51

**Comment by isabellaalstrom** [comment]
So @cerebrate , is the pr you submitted to me a fix until merge in pygrocy or should I wait for the merge there to merge into card?

**Comment by cerebrate** [comment]
Oh, sorry for the confusion. The PR I submitted here’s a fix for an (unrelated) date formatting issue I found when looking into this one. It can be merged anytime.

**Comment by isabellaalstrom** [comment]
Thank you!

**Comment by isabellaalstrom** [comment]
I'll close this issue then, since it should be fixed soon :)
