### ISSUE TITLE
custom element doesn't exist again

### ISSUE THREAD

**Issue by sagresbier** [isabellaalstrom/lovelace-grocy-chores-card#136]
Hello again,
as @karwosts already forked and added new repository, I got this error again.
![image](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/assets/66330777/a72775dd-cb56-4712-978c-45dc2944a2b7)
What happened?

**Comment by karwosts** [comment]
Well there could be any number of reasons your frontend is not finding it. To diagnose, please provide:

* a screenshot of your filesystem showing the grocy-chores-card.js and what path it is in, and include the filesize of the card in the screenshot to confirm it is the right version. 

* a screenshot of your HA config/lovelace/resources settings page showing the chores-card resource configuration.

**Comment by karwosts** [comment]
Actually to clarify, what do you mean you "forked and added new repository"?

What are you trying to achieve? Are you installing from this repo, or trying to run your own fork of this card?

**Comment by robertfgoodworth** [comment]
I've had that happen too, my fix was to redownload (from the hacs component page, top right hand corner 3 dots) both the "Grocy custom component" and this lovelace component.  my grocy cards now works again.

**Comment by sagresbier** [comment]
@robertfgoodworth worked :+1: 
@karwosts : it's working again.
