### ISSUE TITLE
Enhancement Request: Make card translatable

### ISSUE THREAD

**Issue by SebRut** [isabellaalstrom/lovelace-grocy-chores-card#14]

**Comment by isabellaalstrom** [comment]
Do you know if there's some template to show how this is done? I'm guessing it needs to use HA's translations?

**Comment by SebRut** [comment]
I don't have experience with developing lovelace cards but it seems like [this](https://github.com/home-assistant/home-assistant-polymer/blob/8a39d18323a79b85ec1cc59bc746480f8bcf62f0/src/panels/lovelace/cards/hui-thermostat-card.ts#L94) part of code uses localization.

**Comment by isabellaalstrom** [comment]
It seemed too hard to make it work with something like the one HA uses itself, so I made a rough workaround, https://github.com/isabellaalstrom/lovelace-grocy-chores-card/releases/tag/0.1.6
