### ISSUE TITLE
Add Task textboxes missing

### ISSUE THREAD

**Issue by fedefreue** [isabellaalstrom/lovelace-grocy-chores-card#141]
In the latest version, for some reason the textbox for adding a task and the date selector are missing - see below. Has anyone encountered this?

![image](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/assets/63209974/9d7c6b9c-cf24-4063-b958-6836c2a48f1b)

**Comment by karwosts** [comment]
Yes I also see this. 

I know HA developers have been stripping out `paper` elements from the frontend, so I guess these `<paper-input>` elements are no longer preloaded.  Will have to be replaced with something else.

**Comment by fedefreue** [comment]
You beat me to it!

**Comment by fedefreue** [comment]
It works - thanks @karwosts !
