### ISSUE TITLE
0.1.3 not working (empty view)

### ISSUE THREAD

**Issue by cotwild** [isabellaalstrom/lovelace-grocy-chores-card#15]
I wasn't able to get the lovelace-grocy-chores-card to work... so I searched the code and found the problem on line 162, where the script tries to JSON parse, but the items are already parsed...

changing line 162 to the following made the card working:
ORIGINAL: var chores = JSON.parse(entity.attributes.items);
NEW: var chores = entity.attributes.items;

**Comment by LaskaBozzolo** [comment]
Same problem here... I cannot get the card to work and with the debug console in chrome I can see the following even if I cannot understand what that means:

grocy-chores-card.js:162 Uncaught (in promise) SyntaxError: Unexpected token o in JSON at position 1

**Comment by BlueBlueBlob** [comment]
> I wasn't able to get the lovelace-grocy-chores-card to work... so I searched the code and found the problem on line 162, where the script tries to JSON parse, but the items are already parsed...
> 
> changing line 162 to the following made the card working:
> ORIGINAL: var chores = JSON.parse(entity.attributes.items);
> NEW: var chores = entity.attributes.items;

Yes we changed format sensor. No json anymore.
This change was for templating purporse :)

**Comment by isabellaalstrom** [comment]
I will get on this during the week hopefully.
