### ISSUE TITLE
Show only chores due in x days not working (Version 0.1.3)

### ISSUE THREAD

**Issue by cotwild** [isabellaalstrom/lovelace-grocy-chores-card#16]
In the function "calculateDueDate(dueDate)" the following line isn't correct:

OLD: var splitDate = dueDate.split(/[- :]/)
CORRECT: var splitDate = dueDate.split(/[- :T]/)

as dueDate comes in this form:
2020-12-01T00:00:00+00:00

**Comment by isabellaalstrom** [comment]
Thanks!

**Comment by isabellaalstrom** [comment]
https://github.com/isabellaalstrom/lovelace-grocy-chores-card/releases/tag/0.1.5
