### ISSUE TITLE
Good job :)

### ISSUE THREAD

**Issue by BlueBlueBlob** [isabellaalstrom/lovelace-grocy-chores-card#17]
We made some changes in Grocy custom component, like json removed.

I'm interesting in custom card, did you use the boiler-card template ?
I will learn a lot with your cards.

Thanks 👍

**Comment by isabellaalstrom** [comment]
Thank you! I did not use the boiler-card template.

**Comment by BlueBlueBlob** [comment]
Ok I will use your code which seems more simple than boiler-template (because of me, js is not my cup of tea ;) )
Thx to work on grocy.
Can I suggest you to contribute to the custome component, please ? :)
https://github.com/custom-components/grocy
I don't know how, but your js skills will be appreciated :)

Kind regards and good job 👍

**Comment by isabellaalstrom** [comment]
Thanks again. I would contribute to the integration if I had the time, but right now I'm kind of swamped. Thank you yourself for your work!
