### ISSUE TITLE
Request: Wording change

### ISSUE THREAD

**Issue by apmillen** [isabellaalstrom/lovelace-grocy-chores-card#20]
Not a big thing, but maybe 'Scheduled for:' could be changed for 'Due' (So it says 'Due in 4 days' rather than 'Scheduled for: In 4 days')
Alternatively you could just remove the 'In' from 'In 4 Days' so that it says 'Scheduled for: 4 days' and it would still make sense if it were to have a date rather than a due in time.

**Comment by isabellaalstrom** [comment]
I have actually removed this for my self to only have dates for a while, so that should "solve" this issue.
