### ISSUE TITLE
crashes on chores without due date

### ISSUE THREAD

**Issue by oli-f** [isabellaalstrom/lovelace-grocy-chores-card#21]
I have some chores without a due date and the plugin crashes. The entire lovelace UI gets blank.

```
TypeError: a._next_estimated_execution_time is null grocy-chores-card.js:167:28
    set hass/< grocy-chores-card.js:167
    comparefn self-hosted:212
    InsertionSort self-hosted:3508
    MergeSort self-hosted:3564
    sort self-hosted:215
    set hass grocy-chores-card.js:166
    value hui-view.ts:61
    value hui-view.ts:336
    value hui-view.ts:68
    r fire_event.ts:76
    va create-card-element.ts:111

```

**Comment by isabellaalstrom** [comment]
How do you manage to make a chore without an execution time in the Grocy ui? I can't do it.

**Comment by oli-f** [comment]
I have created a periodically chore (in my case every 14 days) and haven't marked it as done yet.
This is what my  entity.attributes.items looks like:
```
0: {
	_chore_id: 5
	_last_done_by: null
	_last_tracked_time: null
	_name: "Test"
	_next_estimated_execution_time: null
	<prototype>: {…}
}
```
Its a rare case, but I suggest to simply filter those out.

**Comment by isabellaalstrom** [comment]
This new release should fix it!
https://github.com/isabellaalstrom/lovelace-grocy-chores-card/releases/tag/0.1.6
