### ISSUE TITLE
Date and time formatting

### ISSUE THREAD

**Issue by BigDoom** [isabellaalstrom/lovelace-grocy-chores-card#23]
Would it be possible to have the date and time customizable to format it according my preference?

For instance today the date shows as 2020-02-17, while I would prefer 17-02-2020, or to make it even more interesting a chore due in two days show it as 'due: in two days'.

Probably best to have the date fields be able to handle templating?

**Comment by isabellaalstrom** [comment]
I can absolutely see this for the future, however I don't have the time right now. I do gladly accept pull requests if someone wants to contribute.

**Comment by clarinetJWD** [comment]
@BigDoom - I didn't do full formatting, but I do have a pull request open that uses default international formatting based on your location settings. Should do what you want! Request #77
