### ISSUE TITLE
select a user per card 

### ISSUE THREAD

**Issue by adtwomey** [isabellaalstrom/lovelace-grocy-chores-card#25]
The chore card does not show who the chore is attached too which makes it harder to determine who's day / job it is to do it. It would be nice to either show the user it's assigned to or select a user per card so I can have a different card for each person doing chores.

**Comment by adtwomey** [comment]
![Screenshot_20200525-210751_Samsung Internet](https://user-images.githubusercontent.com/14849762/82807950-3781ec80-9ecc-11ea-881b-b2578ace9f0a.jpg)

**Comment by isabellaalstrom** [comment]
This actually needs to be implemented in the component, because the sensor doesn't contain information about who is assigned. I can't do anything until the sensor has that information. The only user info the sensor has right now is who did the chore last, in `_last_done_by`
```- _id: 3
  _last_tracked_time: '2020-01-06T00:00:00+00:00'
  _next_estimated_execution_time: '2020-04-05T00:00:00+00:00'
  _name: Clean ac filter
  _last_done_by:
    _id: 2
    _username: Isa
    _first_name: ''
    _last_name: ''
    _display_name: Isa

**Comment by adtwomey** [comment]
Thanks I was thinking that too.

![Screenshot_20200601-205813_Samsung Internet](https://user-images.githubusercontent.com/14849762/83402756-b0dc8a80-a44a-11ea-9322-7c04391a1ac5.jpg)

**Comment by Gibby** [comment]
Would it be possible to add a filter that can be modified later on? 

For instance, first support filtering on `_last_done_by` then when the component is updated to grab who is assigned could add that as a filter?

**Comment by Gibby** [comment]
If you want test this, see my comment at https://github.com/custom-components/grocy/issues/44#issuecomment-669238220

**Comment by isabellaalstrom** [comment]
I will be happy to try this out once your pr has gone through.

**Comment by isabellaalstrom** [comment]
With the new filtering option you can kind of attain this if you name the chores accordingly.
https://github.com/isabellaalstrom/lovelace-grocy-chores-card/releases/tag/0.3.0

**Comment by Gibby** [comment]
Sweet, I am pre-fixing the chore names with the child that it was assigned to. Hopefully in my PR goes through then I can make some of them random.

**Comment by isabellaalstrom** [comment]
This is now possible in the card if you have pre-release of both component and card installed.
https://github.com/isabellaalstrom/lovelace-grocy-chores-card/releases/tag/v1.1.0
Will soon release for real!
