### ISSUE TITLE
Card won't show up

### ISSUE THREAD

**Issue by HeedfulCrayon** [isabellaalstrom/lovelace-grocy-chores-card#37]
The card won't show up... here is the js error
![image](https://user-images.githubusercontent.com/5224972/93147098-cac67400-f6ad-11ea-9c73-f3784d332d62.png)

**Comment by isabellaalstrom** [comment]
Do you have the beta for the component and the beta for the card?

**Comment by HeedfulCrayon** [comment]
Yes, I have the beta on both

**Comment by isabellaalstrom** [comment]
And how about clearing cache?

**Comment by HeedfulCrayon** [comment]
Apparently it is working now after a restart...  Thanks for the help!
