### ISSUE TITLE
Error "TypeError: Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by asdrolf** [isabellaalstrom/lovelace-grocy-chores-card#38]
EDIT (SOLVED?): hmm... ok lol.. i should install "lovelace-grocy-tasks-card" for this :p but it doesnt should fail if there are no chores right?

Hi, i'm triing to integrate lovelace-grocy-chores-card in my HA.

type: 'custom:grocy-chores-card'
entity: sensor.grocy_tasks

Its showing this error when i inspect with developer tools of chrome:

```
CARD-TOOLS 2.1.2 IS INSTALLED  DeviceID: ecf67d67
grocy-chores-card.js:111 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at HTMLElement.render (grocy-chores-card.js:111)
    at HTMLElement.update (app.c5d13434.js:10291)
    at HTMLElement.performUpdate (app.c5d13434.js:10291)
    at HTMLElement._enqueueUpdate (app.c5d13434.js:10291)
```

and if i click on the first line (line 111) it shows this:
```
              )}` : cardTools.LitHtml`<div class="info flex">${this.translate("No chores")}!</div>`}
            </div>
            ${this.notShowing.length > 0 ? cardTools.LitHtml
              `
              <div class="secondary">
                  ${this.translate("Look in Grocy for {number} more chores").replace("{number}", this.notShowing.length)}
              </div>
```

Not sure what it is... my grocy instalation is new, so there is no stock and nothing introduced, there is only one task. should i introduce more more info? what is it tring to load? chores?

Thanks in advance!

**Comment by isabellaalstrom** [comment]
Thanks, no it shouldn't fail with no chores. I'll take a look at that when I have the time.
