### ISSUE TITLE
Grocy sensor only showing 'unknown' 

### ISSUE THREAD

**Issue by Wall-em** [isabellaalstrom/lovelace-grocy-chores-card#39]
When I attempt to add the grocy card, I cannot get it to work. Either it shows up like the screen shot below, or I cannot get the manual card to accept - type: custom:grocy-chores-card either. 

I'm very noobish when it comes to this, but I get no further with Google at this point. 
Sorry if this is the wrong place to put this. 

![Screenshot_20201213-003847_Chrome](https://user-images.githubusercontent.com/75623811/101999619-2d480400-3cdf-11eb-8303-1eac2443c324.jpg)

**Comment by isabellaalstrom** [comment]
You will not get anything in the card if the integration is not loading correctly. Please make an issue over at the integration repo :)
https://github.com/custom-components/grocy/issues/new/choose
