### ISSUE TITLE
Feature request: filter the chores to display

### ISSUE THREAD

**Issue by oncleben31** [isabellaalstrom/lovelace-grocy-chores-card#4]
It could be interesting to have a filter to chose what chores to be displayed.
It could be a filter on the title or other attributes in the chore JSON.
It could be a filter on the userfields value associated to chore, but I think the pyGrocy module doesn't give access to this part of the API.

**Comment by isabellaalstrom** [comment]
This is a good idea. I will keep it until I have more time,

**Comment by Gibby** [comment]
Also just ran into an Issue where I need this

**Comment by isabellaalstrom** [comment]
Latest release contains filtering. You can also choose to remove the filter word from the display.

https://github.com/isabellaalstrom/lovelace-grocy-chores-card/releases/tag/0.3.0
