### ISSUE TITLE
Feature Request: Option to disable TRACK

### ISSUE THREAD

**Issue by GlennGoddard** [isabellaalstrom/lovelace-grocy-chores-card#40]
It would be useful to have the option to disable TRACK so the card could be used to display the status of chores only.

This could be used for users that just need access to see chores and not mark as complete and also for displays for information use only and prevent inadvertent execution.

**Comment by isabellaalstrom** [comment]
Implemented!

**Comment by GlennGoddard** [comment]
I updated to the last version and added:
show_track_button: false
This does not appear to have any effect.

**Comment by isabellaalstrom** [comment]
Have you cleared your cache?

**Comment by GlennGoddard** [comment]
.....I did just now and it works....
Of course after you said that I remembered, it did explicitly say 'clear you cache'.
Thanks

**Comment by GlennGoddard** [comment]
Submitted pull request with update to ReadMe

**Comment by isabellaalstrom** [comment]
I don't see a pr 😅0

**Comment by GlennGoddard** [comment]
I originally did a PR under the DEV branch, but it is not there now.
I just did one on the master this time and it labeled as #2, so I don't know what happened to the 1st.
