### ISSUE TITLE
Filter seems to only allow 1 String

### ISSUE THREAD

**Issue by Soundtech89** [isabellaalstrom/lovelace-grocy-chores-card#44]
I was attempting to update my chores card tonight to filter it based off of 2 different strings: either "Week" or "Yearly". If I use either one on its own, it works as I would expect as I only get the chores with that string in their name. When I use both string, my card shoes "No chores". 

**Working Filter with a single string:**
![Working Filter](https://user-images.githubusercontent.com/10519930/105116017-e0064180-5a97-11eb-8905-c5e7200682af.png)

**Not Working Filter with multiple strings**
![Not Working Filter](https://user-images.githubusercontent.com/10519930/105116015-df6dab00-5a97-11eb-89d0-b49efce3536c.png)

**Comment by isabellaalstrom** [comment]
That is correct, the filter option only takes a string, not a list.
