### ISSUE TITLE
No integration found

### ISSUE THREAD

**Issue by stefancvetkovic** [isabellaalstrom/lovelace-grocy-chores-card#5]
I added into my config file

grocy: url: "http://hassio.local:8123/api/hassio_ingress/xJNwv4F8SBerwLRpJo5ujxNmZb1t39MuWrI-C3fzKxc/api" api_key: "YX6RjEDOY9ecClHPKFLEFl2oiV3OyhLc123437637" sensor: - enabled: true

and when I check out my config it says Integration not found: grocy

**Comment by isabellaalstrom** [comment]
You cannot use the ingress address, you have to specify a port for it and use ip-address:port. However this has nothing to do with the card, but the component :)
