### ISSUE TITLE
Card reports no chores even though sensor contains data

### ISSUE THREAD

**Issue by Cludch** [isabellaalstrom/lovelace-grocy-chores-card#52]
First of all: Thanks a lot for the great card and integration!

However, the card stopped working for me (without an update).
I am using the default user, which has some chores. Some are due and some not. 

The sensor from the integration contains data, thus the integration seems to be working fine.
I tried debugging the card shortly and it seems that this method https://github.com/isabellaalstrom/lovelace-grocy-chores-card/blob/master/grocy-chores-card.js#L222 is not being called or `hass` seems to be `undefined`.
Unfortunately, I have no further knowledge of the Home Assistant framework and internals, therefore I can't tell what might be causing that.

Do you have any idea, what to test or what could be causing that?
This is probably not directly related to the card and more related to some custom integration(?)

Thanks a lot in advance!

**Comment by isabellaalstrom** [comment]
Have you installed the latest version of the card, from just a couple of days ago? Also have you cleared cache in your browser?

**Comment by Cludch** [comment]
Yes to both questions.
The issue started 2-3 weeks ago across all devices. I have also updated to the latest version yesterday and cleared caches / tried private windows.

**Comment by isabellaalstrom** [comment]
That is very weird. I'm afraid I don't know what could be wrong then. Any other custom cards not working? Maybe try a complete reinstall of the card. Should not be the integration if the sensors are showing up correctly.

**Comment by isabellaalstrom** [comment]
just pushed another version now, try that

**Comment by Cludch** [comment]
Yes, that fixed it. Highly appreciate your great work! Thanks
