### ISSUE TITLE
Support filtering on categories for tasks

### ISSUE THREAD

**Issue by isabellaalstrom** [isabellaalstrom/lovelace-grocy-chores-card#54]

**Comment by hillbicks** [comment]
Would be great to either get a filter for categories as a list or alternatively enhance the user filter to only show  chores/tasks **not** assigned to a particular user. 

I created two task categories that will always be done by me, not by my wife. Would be nice to filter these out for her.

**Comment by karwosts** [comment]
Pending implementation in #105
