### ISSUE TITLE
Card does not work off-line

### ISSUE THREAD

**Issue by Mike-Can** [isabellaalstrom/lovelace-grocy-chores-card#56]
This card works fine if I have the HA connected to internet.

I'm assuming that may have something to do with the "LitElement" module.

Are there any dependencies I need to install to make the card work off-line?

I am running HA supervised in docker.  

Thanks

**Comment by isabellaalstrom** [comment]
I will try to fix that it should work offline too.

**Comment by isabellaalstrom** [comment]
Can you please try to install the release v4.0.0b. I have tried using a bundled version of lit.

**Comment by Mike-Can** [comment]
Hi Isabella,

I have have tried the release v4.0.0b. Unfortunately it behaves the same as the older version. As soon as I disconnect the internet an refresh the page, the card disappears and get a red box with  "Custom element doesn't exist: grocy-chores-card."

This is a good and helpful card. Hope you can get it working offline!

Thank you for your efforts!

PS. Just curious, I noticed you have used thomasloven's card-tools customElement in the previous versions. Could you revert back to using that resource? Or installing the dependency locally?  something like this "https://github.com/custom-cards/button-card/issues/43" I have installed the lit package from the zip downloaded from the above link and pointed the import to that module but it did not work.

**Comment by Mike-Can** [comment]
BTW, the card works offline!

**Comment by isabellaalstrom** [comment]
Great to hear it worked now!

**Comment by poxin13** [comment]
Will this be pushed to non-beta builds? It looks like on my end it's trying to pull a dependency from unpkg. I don't see a way to pull in the beta build in HACS.

![image](https://user-images.githubusercontent.com/10375741/219705989-b2c43c83-e93b-4d32-9a3e-caaea95de496.png)
