### ISSUE TITLE
Chores shown on Chrome MacOS but but not on Chrome/HA App on IOS?

### ISSUE THREAD

**Issue by muster021** [isabellaalstrom/lovelace-grocy-chores-card#6]
As the title says, the chores from Grocy shows up fine on the computer (both Safari and Chrome) but not on IOS, neither Chrome/Safari HA app.

**Comment by isabellaalstrom** [comment]
I don't know why this is, it shows up on my ios-app.. Do you get any errors that can help me maybe?

**Comment by isabellaalstrom** [comment]
Should be fixed with https://github.com/isabellaalstrom/lovelace-grocy-chores-card/releases/tag/0.1.3
Please reopen if you're still having problems.
