### ISSUE TITLE
Had to remove ?hacstag=xxxxx to get it to work.

### ISSUE THREAD

**Issue by ThellraAK** [isabellaalstrom/lovelace-grocy-chores-card#66]
It didn't show up for me in lovelace to add a card, and I was poking around on the 'manual' way to add things (after using hacs to install it)

https://my.home-assistant.io/redirect/lovelace_resources

Had

/hacsfiles/lovelace-grocy-chores-card/grocy-chores-card.js?hacstag=xxxxxxx

Removing the "?hacstag=xxxxx"

caused everything to work fine.

**Comment by AlesZurek** [comment]
I can confirm that I have same issue.
After installation by HACS it asked me to reload and I still couldn't uset it.
This removal of the "?hacstag=xxxxx" part helped me

**Comment by isabellaalstrom** [comment]
I don't believe this is a problem in the card, rather in HACS maybe.
