### ISSUE TITLE
Clicking on the "track" link does not do anything

### ISSUE THREAD

**Issue by masey7** [isabellaalstrom/lovelace-grocy-chores-card#7]
Clicking on the "track" link does not do anything. I would expect it to do someting.

![image](https://user-images.githubusercontent.com/3464889/64302814-21ee2080-cf53-11e9-984d-30a1f27f0220.png)

**Comment by masey7** [comment]
@isabellaalstrom , do any configuration is needed for the link to work ?

**Comment by isabellaalstrom** [comment]
Fixed in release 0.1.1. Default userid is now 1, which should be your admin user. You can also specify another user id.
