### ISSUE TITLE
card-tools requirement?

### ISSUE THREAD

**Issue by hockey6611** [isabellaalstrom/lovelace-grocy-chores-card#75]
Hello!
Thank you for your work on the Grocy component and this card. I am working towards integrating grocy more into HA, and this card will help tremendously with that. I noticed in the HACS display [info.md](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/blob/eb2f37fec96767183e26078e290bae349d81e003/info.md?plain=1#L6) page, it states the `card-tools` is required. However, I don't have this installed, and the card seems to be working fine.

I do have `browser-mod` though, would that be why? I also noted the info.md seems a bit out dated compared to the [README.md](https://github.com/isabellaalstrom/lovelace-grocy-chores-card/blob/master/README.md) as displayed in the main github view of the card. If the info.md is indeed old, it seems that [HACS might take that in precedence](https://hacs.xyz/docs/publish/start#infomd) over the README.md file.

**Comment by isabellaalstrom** [comment]
Thank you! Info.md is outdated, as you noticed. I will fix that.
