### ISSUE TITLE
show_days option no longer correctly filters tasks

### ISSUE THREAD

**Issue by clintkev251** [isabellaalstrom/lovelace-grocy-chores-card#82]
Since configuring this card, I've used the attribute `show_days: 0` to hide tasks that are due on future days and this has worked as expected, however after updating to 3.4.0 this no longer seems to work and all chores are shown regardless of due date. I'll include my YAML for the card below for reference:

```
        - type: custom:grocy-chores-card
          entity: sensor.grocy_chores
          title: null
          show_quantity: null
          show_days: 0
          show_assigned: true
          show_last_tracked: true
          show_last_tracked_by: false
          show_track_button: true
```

**Comment by andersstorhaug** [comment]
I think this is the issue, because `0` is treated as "falsy" thus the value is lost.

https://github.com/isabellaalstrom/lovelace-grocy-chores-card/blob/08d21c885e4cc930bda71e7103427d64a9960232/grocy-chores-card.js#L615
