### ISSUE TITLE
Card fails to load on older browsers (fully-kiosk)

### ISSUE THREAD

**Issue by FHeilmann** [isabellaalstrom/lovelace-grocy-chores-card#86]
Hi, 
thanks for creating this card, it's very useful and I enjoy using it on my more up-to-date devices. Unfortunately, on my DIY wall dashboard, running fully kiosk, the card doesn't render at all.

Here's the error:

`grocy-chores-card.js?hacstag=195671060351:427 Uncaught SyntaxError: Unexpected token '='`

I've previously had issues with fully on other cards. Possibly because fully uses some outdated components. My suspicion is that fully is too old to understand `||=` and therefore fails. Would it be possible to change these occurences to "old syntax" (i.e. replace `x ||= y` with `x || (x = y)`) so older browsers can use this card? Feel free to reach out to me if more debugging on old browsers is necessary.

Thanks in advance!

Florian

**Comment by FHeilmann** [comment]
Making those changes (also for any occurrences of `&&=`) allowed the card to appear. Also, this card still requires online access to load the dependencies as described in #56.

**Comment by cdouet** [comment]
Hello,
I have exactly the same issue with the error message "grocy-chores-card.js?hacstag=xyz Uncaught SyntaxError: Unexpected token '='" appearing on my fully kiosk browser, but not on my phone or laptop...
How did you solve that for fully kiosk?
Thanks in advance

**Comment by FHeilmann** [comment]
> Hello, I have exactly the same issue with the error message "grocy-chores-card.js?hacstag=xyz Uncaught SyntaxError: Unexpected token '='" appearing on my fully kiosk browser, but not on my phone or laptop... How did you solve that for fully kiosk? Thanks in advance

It requires changes to the card, I've submitted a pull request #87 to address it.

You also need to make sure your kiosk browser isn't blocked from internet access (like mine was) as this card doesn't ship with its dependencies and needs a working internet connection to download them
