### ISSUE TITLE
A 'show_description' configuration option to display the description under the Chore title

### ISSUE THREAD

**Issue by HStep20** [isabellaalstrom/lovelace-grocy-chores-card#88]
Currently, the card (as far as I can tell) has no option to show the description of a chore. It would be great as an option to have a configuration option which, when enabled, shows the Description of a chore returned by Grocy. 

The Grocy Chores sensor does include the 'description' in it's returned data, so I would think adding it as a line would be relatively straightforward. This would be very helpful for multi-part chores, so the end user (who isn't exposed to the 'grocy backend' at all) can see what needs to be done for larger chores like "Tidy the Kitchen", which includes "Wipe down the counters, Clean the Microwave, Clean the stovetop, and mop the floor" in the description

**Comment by Kixel** [comment]
I'd really like this feature too - i use the description field quite a lot, having that option would make this card even more useful!

**Comment by karwosts** [comment]
Submitted a PR for this feature.
