### ISSUE TITLE
Click on the "track" link does not do anything.

### ISSUE THREAD

**Issue by masey7** [isabellaalstrom/lovelace-grocy-chores-card#9]
![image](https://user-images.githubusercontent.com/3464889/65374905-05ddc500-dc5d-11e9-957a-46256aa7469a.png)

**Comment by isabellaalstrom** [comment]
Do you have the latest version?

**Comment by isabellaalstrom** [comment]
Should be fixed with https://github.com/isabellaalstrom/lovelace-grocy-chores-card/releases/tag/0.1.1
Please reopen if you're still having problems.
