### ISSUE TITLE
"remove_filter" does not filter title when multiple values passed to "filter"

### ISSUE THREAD

**Issue by mattte** [isabellaalstrom/lovelace-grocy-chores-card#90]
When using a list for the "filter" argument, the correct chores are shown, but with the "remove_filter" argument filter set to true, they are still present in the title, example config:
```
type: custom:grocy-chores-card
entity:
  - sensor.grocy_chores
title: Matt's Chores
user_id: 2
filter:
  - 'All: '
  - 'Matt: '
remove_filter: true
```

When changing "filter" to a single string, the expected behavior happens and "All: " is correct removed from the chore title, example config:
```
type: custom:grocy-chores-card
entity:
  - sensor.grocy_chores
title: Matt's Chores
user_id: 2
filter: 'All: '
remove_filter: true
```

**Comment by karwosts** [comment]
Pending fix in #104
