### ISSUE TITLE
Translation for 'Look in Grocy for {number} more items' does not work.

### ISSUE THREAD

**Issue by Aasikki** [isabellaalstrom/lovelace-grocy-chores-card#92]
When a apply a translation for the overflow text 'Look in Grocy for {number} more items', the translation does not work, if the string {number} is included. If I replace "{number}" with the literal number of the remaining items, it will work, but I'd have to include translation for every possible number then.

I suspect this could be because the apostrophes and quotation marks get removed when clicking save in the card config editor, for some reason.

### How to reproduce:
1. Add a chores card to your lovelace dashboard
2. Try to translate 'Look in Grocy for {number} more items', according to the documentation.

Example of yaml that doesn't work:
```
custom_translation:
  'Look in Grocy for {number} more items': "Det finns {number} fler göromål i Grocy"
```

Example of yaml that **does** work:
```
custom_translation:
  Look in Grocy for 3 more items: "Det finns 3 fler göromål i Grocy"
```

I'm not exacly translating this by the way, I'm trying to change the text to "Look at home mobile dashboard for {number} more tasks", as I'm using this on my smart mirror where there's no user input possible.

**Comment by Aasikki** [comment]
**A (bit silly but working) workaround:**
```
custom_translation:
  Look in Grocy for 1 more items: Look in mobile dashboard for 1 more chore
  Look in Grocy for 2 more items: Look in mobile dashboard for 2 more chores
  Look in Grocy for 3 more items: Look in mobile dashboard for 3 more chores
  Look in Grocy for 4 more items: Look in mobile dashboard for 4 more chores
  Look in Grocy for 5 more items: Look in mobile dashboard for 5 more chores
  Look in Grocy for 6 more items: Look in mobile dashboard for 6 more chores
  Look in Grocy for 7 more items: Look in mobile dashboard for 7 more chores
  Look in Grocy for 8 more items: Look in mobile dashboard for 8 more chores
  Look in Grocy for 9 more items: Look in mobile dashboard for 9 more chores
  Look in Grocy for 10 more items: Look in mobile dashboard for 10 more chores
```

**Comment by karwosts** [comment]
Filed PR for a fix.
