### ISSUE TITLE
Error message regarding 'null' details

### ISSUE THREAD

**Issue by cdouet** [isabellaalstrom/lovelace-grocy-chores-card#96]
Hello,

I run HA 2023.4.4 on a Yellow.

I get the following error message:

_Logger: frontend.js.latest.202304111
Source: components/system_log/__init__.py:257
First occurred: 7:26:14 AM (7 occurrences)
Last logged: 10:47:01 AM

http://192.168.1.200:8123/hacsfiles/lovelace-grocy-chores-card/grocy-chores-card.js:34:23 TypeError: null is not an object (evaluating 'entity.state')
http://192.168.1.200:8123/local/kiosk-mode.js?v=1.2.1:57:95 TypeError: null is not an object (evaluating 'e.querySelector')
http://192.168.1.200:8123/local/kiosk-mode.js?v=1.2.1:57:96 Uncaught TypeError: Cannot read properties of null (reading 'querySelector')
http://192.168.1.200:8123/hacsfiles/lovelace-grocy-chores-card/grocy-chores-card.js:34:24 Uncaught TypeError: Cannot read properties of null (reading 'state')_

Can you please advise?

Thanks

**Comment by karwosts** [comment]
Is the sensor enabled for whichever of tasks or chores you're trying to show?

I just set this up in my dev instance and saw similar error, but once I enabled the sensor in the integration it went away (believe it is disabled by default)
